### PR TITLE
Dropping typing dependency

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
Conda gets confused and does not install 3.1.1 per default on my system (python 3.7 / linux64). It's because you switched to `noarch` and typing is only for `py<=35`.

I tried to add a selector but because it's `noarch`, it is not allowed...

I discover the issue after installing `jupyter_conda` and found this error: https://github.com/fcollonval/jupyter_conda/issues/16

I can still force the installation with: `conda install jupyter_conda=3.1.1` but it's not ideal and most people won't do it.

I don't know if there is an alternative to removing `noarch`.

Any idea?

ping @fcollonval

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by fcollonval** [comment]
This is tricky indeed. 

We could choose to drop completely `typing` as dependency as python 2.7 (only version requiring it) is gonna be deprecated in 1 month. Or we switch to a non `noarch` package.

But @dbast beats me on this one, thanks for making the change.

**Comment by dbast** [comment]
Maybe skipping python 2.7 is the better change as Python 2.7 supports ends soon in a few weeks.

**Comment by dbast** [comment]
The 2.7 builds fail anyway, so staying noarch, removing typing and requiring python >=3 should work.

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Review by fcollonval — COMMENTED** [review]
Thanks @dbast and @hadim 

This is also coherent as `notebook>=6` drops support for Python <3.5.

**Pull request merged**
